version: '3.4'

services:
  rentgoapi:
    image: rentgoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - mssqldb
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Pass@123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    build: 
      context: .
      dockerfile: DB.Dockerfile
  